env:
  browser: true
  es2021: true
extends:
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jest/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - react-hooks
  - jest
rules: {
  import/extensions: [0, { js: "always" }],
  import/prefer-default-export: 0,
  jsx-a11y/label-has-associated-control: 0
}
