module.exports = {
  '01d': 'day_clear',
  '01n': 'night_clear',
  '02d': 'day_partial_cloud',
  '02n': 'night_partial_cloud',
  '03d': 'cloudy',
  '03n': 'cloudy',
  '04d': 'cloudy',
  '04n': 'cloudy',
  '09d': 'rain',
  '09n': 'rain',
  '10d': 'day_rain',
  '10n': 'night_rain',
  '13d': 'snow',
  '13n': 'snow',
  '50d': 'mist',
  '50n': 'mist',
  '11d': 'thunder',
  '11n': 'thunder',
};
