name: NodeJS tests linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: set-env
      uses: allenevans/set-env@v2.0.0
      with:
          WEATHER_API_TOKEN: ${{ secrets.WEATHER_API_TOKEN }}

    - name: Build
      run: |
        npm install
        npm run-script build --if-present
